name: Test React Application
 
on: ['pull_request', 'push']

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Using Node 20
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: install and unit test 🚧
        run: 
          yarn add
          yarn test
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: build and run e2e test 🚧
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: npm run build
          start: npm run dev
          wait-on: 'http://localhost:5173'
      