name: Test React Application
 
on: ['pull_request', 'push']

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install and unit test 🚧
        run: 
          yarn add
          yarn test
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: build and run e2e test 🚧
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          build: npm run build
          start: npm start
      